// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package mem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMsg struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgType              int32    `protobuf:"varint,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgData              []byte   `protobuf:"bytes,5,opt,name=msgData,proto3" json:"msgData,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMsg) Reset()         { *m = TestMsg{} }
func (m *TestMsg) String() string { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()    {}
func (*TestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMsg.Unmarshal(m, b)
}
func (m *TestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMsg.Marshal(b, m, deterministic)
}
func (m *TestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg.Merge(m, src)
}
func (m *TestMsg) XXX_Size() int {
	return xxx_messageInfo_TestMsg.Size(m)
}
func (m *TestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg proto.InternalMessageInfo

func (m *TestMsg) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *TestMsg) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *TestMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *TestMsg) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *TestMsg) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *TestMsg) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "mem.TestMsg")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0xbd, 0x0a, 0xc2, 0x40,
	0x0c, 0xc0, 0x71, 0x62, 0xbf, 0x68, 0x70, 0x3a, 0x44, 0x32, 0x38, 0x1c, 0x4e, 0x37, 0xb9, 0xf8,
	0x0a, 0x2e, 0x1d, 0x5c, 0x8e, 0xbe, 0x40, 0xa5, 0xa1, 0x38, 0x84, 0x2b, 0x4d, 0x1c, 0x7c, 0x1c,
	0xdf, 0x54, 0xec, 0x07, 0x8e, 0xbf, 0x84, 0xf0, 0x0f, 0xa2, 0xb1, 0xda, 0x65, 0x9c, 0x92, 0x25,
	0x97, 0x09, 0xcb, 0xf9, 0x03, 0x58, 0xb5, 0xac, 0x76, 0xd7, 0xc1, 0x1d, 0xb1, 0x9c, 0x52, 0x92,
	0xa6, 0x27, 0xf0, 0x10, 0xea, 0xb8, 0xca, 0x9d, 0xb0, 0xb6, 0xa7, 0xb0, 0x5a, 0x27, 0x23, 0xed,
	0x3c, 0x84, 0x3c, 0xfe, 0x07, 0xee, 0x80, 0x85, 0xe8, 0xd0, 0xf4, 0x94, 0xcd, 0x47, 0x0b, 0x1c,
	0x61, 0x25, 0x3a, 0xb4, 0xef, 0x91, 0x29, 0xf7, 0x10, 0x8a, 0xb8, 0x71, 0xdd, 0xdc, 0x3a, 0xeb,
	0xa8, 0xf0, 0x10, 0xf6, 0x71, 0xe3, 0xaf, 0xff, 0x52, 0x9e, 0x9a, 0x9e, 0xca, 0xa5, 0xbf, 0xe8,
	0x51, 0xce, 0xff, 0x5e, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x88, 0xc4, 0x2c, 0xbd, 0x00,
	0x00, 0x00,
}
